package scuttlebutt.event;

import java.io.Serializable;
import java.security.PublicKey;

/**
 * Content of an event generated by the stores
 */
public class Content implements Serializable {

  private static final long serialVersionUID = 3655378693727182060L;

  /** Available content types */
  public static enum ContentType {
    DATA, FOLLOW, BLOCK, UNFOLLOW, UNBLOCK
  };

  /** Type of the content */
  private ContentType type;

  /** Actual data of the content */
  private String data;

  /** Store to which the (UN)FOLLOW/(UN)BLOCK events refer */
  private PublicKey who;


  public Content(String data) {
    this.type = ContentType.DATA;
    this.data = data;
  }


  public Content(ContentType type, PublicKey who) {
    this.type = type;
    this.who = who;
  }


  public ContentType getType() {
    return type;
  }


  public void setType(ContentType type) {
    this.type = type;
  }


  public String getData() {
    return data;
  }


  public void setData(String data) {
    this.data = data;
  }


  public PublicKey getWho() {
    return who;
  }


  public void setWho(PublicKey who) {
    this.who = who;
  }

}
