package scuttlebutt.exception;

/**
 * Exception generated by cryptographic functions
 */
public class CryptoException extends Exception {

  private static final long serialVersionUID = 6641684951844557290L;

  public CryptoException(Exception e) {
    super(e);
  }

}
