package scuttlebutt.exception;

/**
 * Exception generated by serialization functions
 */
public class SerializationException extends Exception {
  private static final long serialVersionUID = -1929325539738911749L;


  public SerializationException(Exception e) {
    super(e);
  }

}
